apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dotnetwebapi
resources:
- ../../base
- namespace.yaml
- ingress.yaml
images:
- name: dotnetwebapi-api
  newName: ghcr.io/nickpeachey/dotnetwebapi-api
  newTag: c12df567fd74
